name: "Consensus Warn"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    permissions:
      pull-requests: write # For reading the PR and posting comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: orijtech/consensuswarn@main
        with:
          roots: 'github.com/elysiumstation/blackfury/v13/app.Blackfury.DeliverTx,github.com/elysiumstation/blackfury/v13/app.Blackfury.BeginBlocker,github.com/elysiumstation/blackfury/v13/app.Blackfury.EndBlocker'
